Repository datalayer/helm-charts, pull requests merged in 2024-11, with the labels that each got.

#56 Add support for azure NFS storage
  charts/datalayer-ceph-cluster/values.yaml
  charts/datalayer-ceph-filesystem/values.yaml
  charts/datalayer-ceph-operator/toolbox.yaml
  charts/datalayer-iam/Chart.yaml
  charts/datalayer-iam/README.md
  charts/datalayer-iam/values.yaml
  charts/datalayer-jupyter/Chart.yaml
  charts/datalayer-jupyter/README.md
  charts/datalayer-jupyter/tests/deployment_test.yaml
  charts/datalayer-jupyter/values.yaml
  charts/datalayer-operator/Chart.yaml
  charts/datalayer-operator/README.md
  charts/datalayer-operator/templates/deployment.yaml
  charts/datalayer-operator/values.yaml
  charts/datalayer-shared-filesystem/Chart.yaml
  charts/datalayer-shared-filesystem/README.md
  charts/datalayer-shared-filesystem/README.md.gotmpl
  charts/datalayer-shared-filesystem/templates/_helpers.yaml
  charts/datalayer-shared-filesystem/templates/shared-storage.yaml
  charts/datalayer-shared-filesystem/templates/storage-class.yaml
  charts/datalayer-shared-filesystem/tests/filesystem_test.yaml
  charts/datalayer-shared-filesystem/values.yaml
Labels: enhancement

#57 docs: helm
  charts/datalayer-iam/README.md
  charts/datalayer-jupyter/README.md
  charts/datalayer-observer/README.md
  charts/datalayer-operator/README.md
  charts/datalayer-shared-filesystem/README.md
Labels: documentation

#58 chore: share name for the azure shared storage
  charts/datalayer-jupyter/Chart.yaml
  charts/datalayer-jupyter/README.md
  charts/datalayer-jupyter/templates/serviceaccount.yaml
  charts/datalayer-shared-filesystem/README.md
  charts/datalayer-shared-filesystem/templates/storage-class.yaml
  charts/datalayer-shared-filesystem/values.yaml
Labels: enhancement

#59 Bump operator version
  charts/datalayer-operator/Chart.yaml
  charts/datalayer-operator/README.md
  charts/datalayer-operator/values.yaml
Labels: release

#60 Fix creating snapshot
  charts/datalayer-operator/templates/deployment.yaml
  charts/datalayer-shared-filesystem/templates/shared-storage.yaml
Labels: bug

#61 iam: initial credits
  charts/datalayer-iam/Chart.yaml
  charts/datalayer-iam/README.md
  charts/datalayer-iam/tests/deployment_test.yaml
  charts/datalayer-iam/values.yaml
  charts/datalayer-operator/README.md
Labels: enhancement

#62 chore: add linkedin env var
  charts/datalayer-iam/tests/deployment_test.yaml
  charts/datalayer-iam/values.yaml
Labels: enhancement

#63 chore: jupyterhub + bump datalayer-operator + x api
  charts/datalayer-iam/README.md
  charts/datalayer-iam/tests/deployment_test.yaml
  charts/datalayer-iam/values.yaml
  charts/datalayer-operator/Chart.yaml
  charts/datalayer-operator/README.md
  charts/datalayer-operator/values.yaml
  charts/jupyterhub/Makefile
  charts/jupyterhub/README.md
  charts/jupyterhub/values-auth-dummy.yaml
  charts/jupyterhub/values-auth-generic.yaml
  charts/jupyterhub/values-auth-pam.yaml
  charts/jupyterhub/values-auth-tmp.yaml
  charts/jupyterhub/values-database.yaml
  charts/jupyterhub/values-keycloak-eks.yaml
  charts/jupyterhub/values-keycloak-minikube.yaml
  charts/jupyterhub/values-keycloak.yaml
  charts/jupyterhub/values-minikube.yaml
  charts/jupyterhub/values.yaml
Labels: feature
