Repository datalayer/helm-charts, pull requests merged in 2024-10, with the labels that each got.

#42 Ceph Cluster Name
  charts/datalayer-ceph-cluster/values.yaml
  charts/datalayer-ceph-storage/README.md
  charts/datalayer-ceph-storage/templates/users-storage.yaml
  charts/datalayer-jupyter/README.md
  charts/datalayer-observer/README.md
  charts/datalayer-operator/README.md
Labels: enhancement

#43 chore: ceph prepare
  charts/datalayer-ceph-storage/templates/users-storage.yaml
Labels: enhancement

#44 Add vault config
  charts/datalayer-operator/values.yaml
Labels: enhancement

#46 Fix for Operator + Bump versions
  charts/datalayer-ceph-filesystem/Chart.yaml
  charts/datalayer-ceph-filesystem/README.md
  charts/datalayer-ceph-filesystem/README.md.gotmpl
  charts/datalayer-ceph-filesystem/templates/users-storage.yaml
  charts/datalayer-ceph-filesystem/values.yaml
  charts/datalayer-ceph-operator/README.md
  charts/datalayer-ceph-operator/README.md.gotmpl
  charts/datalayer-ceph-operator/toolbox.yaml
  charts/datalayer-ceph-operator/values.yaml
  charts/datalayer-iam/Chart.yaml
  charts/datalayer-jupyter/Chart.yaml
  charts/datalayer-mailer/values.yaml
  charts/datalayer-operator/Chart.yaml
  charts/datalayer-operator/README.md
  charts/datalayer-operator/templates/deployment.yaml
  charts/datalayer-operator/values.yaml
Labels: release, fix

#47 release 1.0.2
  charts/datalayer-iam/README.md
  charts/datalayer-iam/values.yaml
  charts/datalayer-jupyter/README.md
  charts/datalayer-jupyter/tests/deployment_test.yaml
  charts/datalayer-jupyter/values.yaml
  charts/datalayer-mailer/README.md
  charts/datalayer-operator/README.md
  charts/datalayer-operator/values.yaml
Labels: release

#50 refac: xpu.datalayer.io labels
  charts/jupyterpool/templates/deployment.yaml
Labels: enhancement

#51 Add env in jp-env spec
  charts/datalayer-operator/templates/jupyter-environment.yaml
Labels: enhancement

#52 Set volume sizes for pulsar and loki to fit 2^x azure billing rule
  charts/datalayer-observer/values.yaml
  charts/datalayer-pulsar/values-any.yaml
Labels: enhancement
