Repository datalayer/helm-charts, pull requests merged in 2024-12, with the labels that each got.

#68 Add kafka and falco
  charts/datalayer-falco/README.md
  charts/datalayer-falco/values-any.yaml
  charts/datalayer-falco/values.yaml
  charts/datalayer-kafka/Chart.yaml
  charts/datalayer-kafka/README.md
  charts/datalayer-kafka/templates/falco-topic.yaml
  charts/datalayer-kafka/templates/kafka-metrics.yaml
  charts/datalayer-kafka/templates/kafka-podmonitors.yaml
  charts/datalayer-kafka/templates/kafka-prometheus-rules.yaml
  charts/datalayer-kafka/templates/kafka.yaml
  charts/datalayer-kafka/values.yaml
  charts/datalayer-observer/values.yaml
Labels: enhancement

#70 bump: iam jupyter and operator docker versions
  charts/datalayer-iam/Chart.yaml
  charts/datalayer-iam/README.md
  charts/datalayer-iam/tests/deployment_test.yaml
  charts/datalayer-iam/values.yaml
  charts/datalayer-jupyter/Chart.yaml
  charts/datalayer-jupyter/README.md
  charts/datalayer-jupyter/tests/deployment_test.yaml
  charts/datalayer-jupyter/values.yaml
  charts/datalayer-kafka/README.md
  charts/datalayer-observer/README.md
  charts/datalayer-operator/Chart.yaml
  charts/datalayer-operator/README.md
  charts/datalayer-operator/values.yaml
Labels: release

#71 fix: env var + bump iam version
  charts/datalayer-iam/README.md
  charts/datalayer-iam/templates/deployment.yaml
  charts/datalayer-iam/tests/deployment_test.yaml
  charts/datalayer-iam/values.yaml
  charts/datalayer-jupyter/templates/deployment.yaml
  charts/datalayer-operator/templates/deployment.yaml
Labels: fix

#72 chore: add DATALAYER_AVAILABLE_KERNELS_MAX_LIFE_SEC and DATALAYER_KERNELS_RUN_HOOKS configs
  charts/datalayer-iam/Chart.yaml
  charts/datalayer-operator/Chart.yaml
  charts/datalayer-operator/README.md
  charts/datalayer-operator/values.yaml
Labels: feature

#73 Fix falco deployment
  charts/datalayer-falco/values-any.yaml
  charts/datalayer-kafka/templates/kafka-podmonitors.yaml
  charts/datalayer-kafka/templates/kafka-prometheus-rules.yaml
  charts/datalayer-kafka/templates/kafka.yaml
  charts/datalayer-kafka/values.yaml
Labels: bug

#74 chore: kafka and falco affinity
  charts/datalayer-falco/values-any.yaml
  charts/datalayer-kafka/templates/kafka.yaml
  charts/datalayer-operator/tests/deployment_test.yaml
Labels: enhancement

#75 chore: kafka raft
  charts/datalayer-kafka/Chart.yaml
  charts/datalayer-kafka/templates/kafka-nodepool.yaml
  charts/datalayer-kafka/templates/kafka.yaml
  charts/datalayer-kafka/values.yaml
Labels: enhancement
