Repository datalayer/helm-charts, pull requests merged in 2024-09, with the labels that each got.

#31 Add service account for operator-companion
  charts/datalayer-operator/templates/companion-role.yaml
  charts/datalayer-operator/templates/companion-rolebinding.yaml
  charts/datalayer-operator/templates/companion-serviceaccount.yaml
Labels: enhancement

#32 Combine multiline log into single entry
  charts/datalayer-observer/templates/logs-collector.yaml
Labels: enhancement

#33 Add nodeSelector on autorecovery service
  charts/datalayer-pulsar/values-any.yaml
Labels: bug

#34 Add values for datashim charts
  charts/datalayer-datashim/README.md
  charts/datalayer-datashim/values-any.yaml
  charts/datalayer-pulsar/values.yaml
Labels: enhancement

#35 chore: add vault env vars
  charts/datalayer-iam/README.md
  charts/datalayer-iam/tests/deployment_test.yaml
  charts/datalayer-iam/values.yaml
  charts/datalayer-observer/README.md
  charts/datalayer-operator/README.md
  charts/datalayer-operator/tests/deployment_test.yaml
  charts/datalayer-operator/values.yaml
Labels: enhancement

#36 Release: 1 0 0
  charts/datalayer-iam/Chart.yaml
  charts/datalayer-iam/README.md
  charts/datalayer-iam/values.yaml
  charts/datalayer-jupyter/Chart.yaml
  charts/datalayer-jupyter/README.md
  charts/datalayer-jupyter/tests/deployment_test.yaml
  charts/datalayer-jupyter/values.yaml
  charts/datalayer-operator/Chart.yaml
  charts/datalayer-operator/README.md
  charts/datalayer-operator/values.yaml
Labels: enhancement

#37 fix: operator test
  charts/datalayer-operator/README.md
  charts/datalayer-operator/tests/deployment_test.yaml
Labels: fix

#39 Add ceph users storage
  charts/datalayer-ceph-storage/templates/users-storage.yaml
  charts/datalayer-operator/values.yaml
Labels: enhancement

#40 chore: use 4Gi disk
  charts/datalayer-ceph-cluster/values.yaml
  charts/datalayer-ceph-storage/templates/users-storage.yaml
Labels: enhancement

#41 Parametrize user ceph storage
  charts/datalayer-ceph-storage/templates/users-storage.yaml
  charts/datalayer-ceph-storage/values.yaml
  charts/datalayer-jupyter/tests/deployment_test.yaml
  charts/datalayer-jupyter/values.yaml
  charts/datalayer-operator/templates/deployment.yaml
  charts/datalayer-operator/templates/jupyter-content.yaml
  charts/datalayer-operator/templates/jupyter-environment.yaml
  charts/datalayer-operator/templates/jupyterpool.yaml
  charts/datalayer-operator/values.yaml
Labels: enhancement
