Repository datalayer/helm-charts, pull requests merged in 2025-01, with the labels that each got.

#77 Fix: observer run host
  charts/datalayer-iam/README.md
  charts/datalayer-iam/tests/deployment_test.yaml
  charts/datalayer-iam/values.yaml
  charts/datalayer-observer/templates/ingress.yaml
Labels: fix

#78 chore: observer helper
  charts/datalayer-observer/templates/_helpers.yaml
Labels: enhancement

#80 Fix grafana and otel settings
  charts/datalayer-observer/templates/collector.yaml
  charts/datalayer-observer/templates/logs-collector.yaml
  charts/datalayer-observer/values.yaml
Labels: bug

#81 karpenter: do not disrupt services
  charts/datalayer-iam/Chart.yaml
  charts/datalayer-iam/templates/deployment.yaml
  charts/datalayer-jupyter/Chart.yaml
  charts/datalayer-jupyter/templates/deployment.yaml
  charts/datalayer-library/Chart.yaml
  charts/datalayer-library/templates/deployment.yaml
  charts/datalayer-operator/Chart.yaml
  charts/datalayer-operator/templates/deployment.yaml
  charts/datalayer-spacer/Chart.yaml
  charts/datalayer-spacer/templates/deployment.yaml
Labels: enhancement

#84 Add kafka as pub-sub
  charts/datalayer-iam/Chart.yaml
  charts/datalayer-iam/values.yaml
  charts/datalayer-jupyter/Chart.yaml
  charts/datalayer-jupyter/values.yaml
  charts/datalayer-kafka/templates/email-error-topic.yaml
  charts/datalayer-kafka/templates/email-invite-topic.yaml
  charts/datalayer-kafka/templates/kernel-snapshots-topic.yaml
  charts/datalayer-kafka/templates/usage-topic.yaml
  charts/datalayer-library/Chart.yaml
  charts/datalayer-mailer/Chart.yaml
  charts/datalayer-manager/Chart.yaml
  charts/datalayer-operator/Chart.yaml
  charts/datalayer-operator/values.yaml
  charts/datalayer-spacer/Chart.yaml
Labels: enhancement

#85 chore: use DATALAYER_SHARED_FS_VOLUME_CLAIM_NAME
  charts/datalayer-iam/README.md
  charts/datalayer-jupyter/README.md
  charts/datalayer-kafka/README.md
  charts/datalayer-library/README.md
  charts/datalayer-library/templates/deployment.yaml
  charts/datalayer-library/values.yaml
  charts/datalayer-mailer/README.md
  charts/datalayer-manager/README.md
  charts/datalayer-observer/README.md
  charts/datalayer-operator/README.md
  charts/datalayer-operator/templates/deployment.yaml
  charts/datalayer-shared-filesystem/templates/shared-storage.yaml
  charts/datalayer-spacer/README.md
  charts/datalayer-spacer/templates/deployment.yaml
  charts/datalayer-spacer/values.yaml
Labels: feature

#86 Fix image version
  charts/datalayer-iam/values.yaml
  charts/datalayer-jupyter/values.yaml
  charts/datalayer-library/values.yaml
  charts/datalayer-manager/values.yaml
  charts/datalayer-operator/values.yaml
  charts/datalayer-spacer/values.yaml
Labels: bug

#87 fix: jupyter-server
  charts/jupyter-server/templates/_helpers.yaml
  charts/jupyter-server/templates/ingress.yaml
  charts/jupyter-server/values-any.yaml
  charts/jupyter-server/values.yaml
Labels: fix

#88 Fix typo in kafka config name
  charts/datalayer-iam/values.yaml
  charts/datalayer-jupyter/values.yaml
  charts/datalayer-operator/values.yaml
Labels: bug

#91 Release: 2025 01 29
  charts/datalayer-iam/Chart.yaml
  charts/datalayer-iam/README.md
  charts/datalayer-iam/tests/deployment_test.yaml
  charts/datalayer-iam/values.yaml
  charts/datalayer-jupyter/Chart.yaml
  charts/datalayer-jupyter/README.md
  charts/datalayer-jupyter/tests/deployment_test.yaml
  charts/datalayer-jupyter/values.yaml
  charts/datalayer-operator/Chart.yaml
  charts/datalayer-operator/README.md
  charts/datalayer-operator/tests/deployment_test.yaml
  charts/datalayer-operator/values.yaml
  charts/datalayer-shared-filesystem/templates/shared-storage.yaml
Labels: release
